---
all:
 vars:

  # GKE cluster variables
  gcp_project: packmybag        # ID of GCP Project
  gcp_auth_kind: serviceaccount            # Do not change
  gcp_cred_file: /home/joao/keys/packmybag-592e3f998351.json   # Path to service account keys (json file downloaded from GCP)

  gcp_zone: us-central1-a
  gcp_image_type: ubuntu_containerd
  gcp_machine_type: e2-standard-2      # Can be changed if necessary
  gcp_disk_size_gb: 100                # Can be changed if necessary
  gcp_initial_node_count: 2            # Number of nodes to create. Can be changed if necessary


  # APP variables
  app_ip: app_ip # Needs to be updated everytime
  gateway_ip: 34.135.8.164
  app_port: 80 # Needs to be updated
  numthreads: 50

  packmybag_namespace: gke_packmybag_us-central1-a_packmybag-cluster
