apiVersion: apps/v1
kind: Deployment
metadata:
  name: recomendacoes-deployment
spec:
  selector:
    matchLabels:
      app: recomendacoes
  template:
    metadata:
      labels:
        app: recomendacoes
    spec:
      containers:
      - name: recomendacoes-container
        image: packmybag/webplataform:recomendacoes
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/recomendacoes"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "postgres"