apiVersion: apps/v1
kind: Deployment
metadata:
  name: encomendas-deployment
spec:
  selector:
    matchLabels:
      app: encomendas
  template:
    metadata:
      labels:
        app: encomendas
    spec:
      containers:
      - name: catalogo-container
        image: joaoppc2002/catalogo:latest
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/encomenda"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "postgres"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
