---
# Playbook to deploy recomendacoes service
- name: recomendacoes deploy
  shell: kubectl apply -f roles/recomendacoes_deploy/k8s/deploy.yml --validate=false

- name: recomendacoes service
  shell: kubectl apply -f roles/recomendacoes_deploy/k8s/service.yml --validate=false

- name: Wait for recomendacoes service objects to be ready
  command: kubectl get pods
  register: kubectl_get_pods
  until: "{{ kubectl_get_pods.stdout_lines[1:] | select('search', '1/1') | list | length == kubectl_get_pods.stdout_lines[1:] | length }}"
  retries: 30
  delay: 5
