apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificacoes-deployment
spec:
  selector:
    matchLabels:
      app: notificacoes
  template:
    metadata:
      labels:
        app: notificacoes
    spec:
      containers:
      - name: notificacoes-container
        image: packmybag/webplataform:notificacoes
        ports:
        - containerPort: 8086
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/notificacoes"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "postgres"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: "notificacoesService"
        - name: SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET
          value: "earliest"
