---
# Playbook to deploy encomendas service
- name: encomendas deploy
  shell: kubectl apply -f roles/encomendas_deploy/k8s/deploy.yml --validate=false

- name: encomendas service
  shell: kubectl apply -f roles/encomendas_deploy/k8s/service.yml --validate=false

- name: Wait for encomendas service objects to be ready
  command: kubectl get pods
  register: kubectl_get_pods
  until: "{{ kubectl_get_pods.stdout_lines[1:] | select('search', '1/1') | list | length == kubectl_get_pods.stdout_lines[1:] | length }}"
  retries: 30
  delay: 5
