---
# Playbook to deploy notificacoes service
- name: notificacoes deploy
  shell: kubectl apply -f roles/notificacoes_deploy/k8s/deploy.yml --validate=false

- name: notificacoes service
  shell: kubectl apply -f roles/notificacoes_deploy/k8s/service.yml --validate=false

- name: Wait for notificacoes service objects to be ready
  command: kubectl get pods
  register: kubectl_get_pods
  until: "{{ kubectl_get_pods.stdout_lines[1:] | select('search', '1/1') | list | length == kubectl_get_pods.stdout_lines[1:] | length }}"
  retries: 30
  delay: 5
