apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway-container
          image: packmybag/webplataform:apigateway
          env:
            - name: CATALOGO_SERVICE_URL
              value: "http://catalogo-service:8081/api/catalogo"
            - name: ENCOMENDA_SERVICE_URL
              value: "http://encomendas-service:8082/api/encomendas"
            - name: FAVORITOS_SERVICE_URL
              value: "http://favoritos-service:8083/api/favoritos"
            - name: RECOMENDACOES_SERVICE_URL
              value: "http://recomendacoes-service:8084/api/recomendacoes"
            - name: CESTO_SERVICE_URL
              value: "http://cart-service:8085/api/cart"
            - name: NOTIFICACOES_SERVICE_URL
              value: "http://notificacoes-service:8086/api/notificacoes"
            - name: UTILIZADORES_SERVICE_URL
              value: "http://utilizadores-service:8087/api/utilizadores"
          ports:
            - containerPort: 8888